### ISSUE TITLE
No module named 'cryptotools.BTC'

### ISSUE THREAD

**Issue by RobinNosheen** [FocSon/Bitcoin_Puzzle_Bruteforce#1] opened 2023-01-17 10:16 UTC
It asking for cryptotools.BTC module but when i install then this error is showing.

ERROR: Could not find a version that satisfies the requirement cryptotools.BTC (from versions: none)
ERROR: No matching distribution found for cryptotools.BTC

**Comment by FocSon** [comment] 2023-01-17 10:24
> It asking for cryptotools.BTC module but when i install then this error is showing.
> 
> ERROR: Could not find a version that satisfies the requirement cryptotools.BTC (from versions: none)
> ERROR: No matching distribution found for cryptotools.BTC

Did you installed all dependencies from the requirement.txt file ?

Try this comment at the project root.
For more contexte you can refer to the readme.md file.

```shell
pip3 install -r requirements.txt
```

Hope this help, don't hesitate if you have any other questions !

**Comment by RobinNosheen** [comment] 2023-01-17 10:28
cloning is already done and ecdsa base58 Requirement already satisfied but still facing the same error No module named 'cryptotools.BTC'

**Comment by FocSon** [comment] 2023-01-17 10:41
> cloning is already done and ecdsa base58 Requirement already satisfied but still facing the same error No module named 'cryptotools.BTC'

I'll look by my own, I'll come back when I've found something.

**Comment by FocSon** [comment] 2023-01-17 21:59
> cloning is already done and ecdsa base58 Requirement already satisfied but still facing the same error No module named 'cryptotools.BTC'

I've tried to reproduce the issue, but I can't manage to get the error.
Be sure to have git installed. cryptotools.BTC isn't a pip dependency, it is a git repo based dependency.

![image](https://user-images.githubusercontent.com/24611821/213020418-a64945bf-8b71-4fcd-8122-46ac8b620907.png)

Could you give me the history of the commands you enter ?

My command history to run the program :
```shell
$ git clone https://github.com/FocSon/Bitcoin_Puzzle_Bruteforce.git
$ cd Bitcoin_Puzzle_Bruteforce/
$ pip3 install -r requirements.txt
$ python3 puzzle.py
```

**Comment by RobinNosheen** [comment] 2023-01-17 22:05
This error is shows when i enter the command of python puzzle.py

C:\Users\more_\Downloads\Compressed\Bitcoin_Puzzle_Bruteforce-main>python puzzle.py
Traceback (most recent call last):
  File "C:\Users\more_\Downloads\Compressed\Bitcoin_Puzzle_Bruteforce-main\puzzle.py", line 10, in <module>
    from cryptotools.BTC import PrivateKey, Address
ModuleNotFoundError: No module named 'cryptotools.BTC'

**Comment by FocSon** [comment] 2023-01-18 18:26
Let's try one last (I hope) thing.
Could you check your version of python please ?
You need to have at least python v3.

```shell
python --version
```

For exemple, here is my version :
![image](https://user-images.githubusercontent.com/24611821/213261679-822ccb3d-7921-4cf7-83a8-39f6db032bac.png)

I've tried on my own to install it on a Windows OS and it worked.
Make sure that git and pip are installed.
I allow myself to remind you that git is used by pip to install the cryptotools.BTC dependency.

**Comment by FocSon** [comment] 2023-02-01 14:13
Without any further response, I'll close this thread.
If the issue is not solved, feel free to open a new one.

I hope that your issue is resolved.
Thanks.

**Closed as completed by FocSon** 2023-02-01 14:13 UTC
